### ISSUE TITLE
Remove RFN

### ISSUE THREAD

**Issue by davelab6** [simoncozens/silson#1]
https://github.com/simoncozens/silson/blob/master/LICENSE#L2

Please don't use RFNs on Github, it makes forking and modifying the fonts infringing; it also means web font users must rename the fonts if they subset them, which sucks

**Comment by n7s** [comment]
I suggest reading through the FAQ and the Web Fonts and Reserved Font Names paper to make your own decision with all the facts and rationale about RFNs: http://scripts.sil.org/OFL-FAQ_web

RFNs are optional but they actually serve a purpose in various cases. (Document reflow issues, changes in coverage and features, unexpected bugs and support burdens coming from derivative versions are then clearly distinct from the canonical version because they have different unique names.)

Some people argue that uncontrolled forking, redistribution and publication of end-user facing fonts under the exact same name as the original is less than ideal.  IOW breaking the namespace for end-users and other designers (or the Knuthian adage: you can modify it but please don't create chaos).

Having webfont services publish truncated subsets of a font (or with broken smarts) under the exact same name as the original for "optimization" purposes is also less than ideal. 

When developing an open font collaboratively in a public repository, you can also use a development name that is different from the release name which users expect to be stable. 

(Documenting changes in a FONTLOG.txt file is recommended but not required).

**Comment by davelab6** [comment]
> When developing an open font collaboratively in a public repository, you can also use a development name that is different from the release name which users expect to be stable.

For people keen on RFNs, I think this is essential :)

**Comment by simoncozens** [comment]
The web fonts / RFN paper says that I can give any webfont service a written agreement to use the RFN in subsets (should I ever get to that stage). But I would rather forks not have the same name. That suggests to me that an RFN _is_ what I want.

I don't understand the benefits of a different development/release name - could you explain?

**Comment by davelab6** [comment]
Well, if I fork this and then modify it, the first modification I must make
is to change the family name in all font files (sources and thus then in
binaries) before I actually change anything else. And then when I sent you
a PR, you must cherry pick the changes if you wish to avoid merging in my
name change.

**Comment by davelab6** [comment]
So, if you declare an RFN for a 'release name' that you'll use, but the
source files and 'temporary' development binaries use another name, this
avoids that rigmarole.

But I think you're better off just using a single project name, and using
your intrinsic moral authority as project founder/leader and potentially
trademark claims to coerce any derivatives that use your project name in a
way you don't like.

I can see that SIL and others they spoke to when drafting the OFL are
concerned about wasting time with supporting broken derivatives of their
fonts, or defending registered trademarks with copyright licensing, and so
on, but I think the majority of libre font projects are much more informal
and the risks and concerns aren't as important to most libre font
developers - like yourself with this project - as they are to formal
organizations. And even then, I don't think its a big deal. "Linux" is a
registered trade mark and it works well to have forks that don't have to
bother renaming everything (cf. https://mjg59.dreamwidth.org/38136.html -
or indeed, how many distros modify the kernel without a trademark license?
:)
